# Generated by Django 4.0.6 on 2022-07-24 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime(2022, 7, 23, 23, 44, 0, 537362))),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime(2022, 7, 23, 23, 44, 0, 536362))),
            ],
        ),
    ]
