# Generated by Django 4.0.6 on 2022-07-24 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 24)),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 24)),
        ),
    ]
