# Generated by Django 4.0.6 on 2022-07-25 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_despesas_data_alter_receitas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevistos'), ('O', 'Outros')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 25)),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 25)),
        ),
    ]
