# Generated by Django 4.0.6 on 2022-07-26 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_despesas_categoria_alter_despesas_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('O', 'Outros'), ('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevistos')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
    ]
