# Generated by Django 4.0.6 on 2022-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_despesas_categoria_alter_despesas_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(),
        ),
    ]
